apiVersion: v1
kind: ConfigMap
metadata:
  name: multimap
data:
  given: Nigel
  family: Poulton

...  
apiVersion: v1
kind: Pod
metadata:
  name: cmvol
spec:
  volumes:
    - name: volmap
      configMap:
        name: multimap
  containers:
    - name: ctr
      image: nginx
      volumeMounts:
        - name: volmap
          mountPath: /etc/name