apiVersion: v1
kind: Service
metadata:
 name: xxx
spec:
 type: NodePort
 selector:
  app: xxx
 ports:
  - protocol: TCP
    port: [80]
    targetPort: [8080]
    nodePort: xxx

...
apiVersion: v1
kind: Service
metadata:
  name: cloud-lb
spec:
  type: LoadBalancer
  selector:
    chapter: services
  ports:
  - port: 9000
    targetPort: 8080